"""
Django settings for FitZone project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carpeta generada por "npm run build" en el frontend (index.html + assets/).
# Django la sirve directamente para que el sitio y la API vivan en el mismo dominio.
FRONTEND_DIST_DIR = BASE_DIR / 'fitzone-frontend' / 'dist'


# Esto busca el archivo .env y lo lee
load_dotenv()

# Así la lee Django de manera segura:
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

# ==============================================================================
# 1. HARDENING (CONFIGURACIÓN DE SEGURIDAD EXTREMA)
# ==============================================================================
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Se lee desde el .env; solo se admite un valor de desarrollo automático si DEBUG=True.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-set-SECRET_KEY-in-.env'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY no está definida. Configúrala en el archivo .env antes de desplegar con DEBUG=False.'
        )

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    # Django Base Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third Party Security & API Apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'simple_history',
    # 🚀 Tus Aplicaciones Modulares del E-commerce
    'core',
    'autenticacion',
    'catalogo',
    'carrito',
    'pagos',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Siempre primero para autorizar a React
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Sirve /static/ (assets de React + admin) en producción
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Permitir la comunicación segura con React en modo desarrollo
# Apagamos el permiso masivo
CORS_ALLOW_ALL_ORIGINS = False

# Autorizamos únicamente a los orígenes definidos en .env (por defecto, el servidor local de React)
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')

# Permitir que viajen encabezados de autenticación (Tokens)
CORS_ALLOW_CREDENTIALS = True

# Forzar HTTPS y mitigar fugas de datos
# En producción, define SECURE_SSL_REDIRECT=True en el .env (déjalo en False solo para desarrollo local sin HTTPS)
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
# HSTS: dejar en 0 hasta confirmar que el dominio sirve HTTPS de forma estable (una vez
# activado, los navegadores recuerdan usar HTTPS por este tiempo, incluso si el sitio falla).
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
# Opcionales y más agresivos que SECURE_HSTS_SECONDS: solo actívalos si estás seguro de que
# TODOS los subdominios sirven HTTPS (SUBDOMAINS) y de que quieres entrar a la lista de
# preload de los navegadores de forma prácticamente irreversible (PRELOAD).
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

# ==============================================================================
# 2. LOGS (REGISTRO CENTRALIZADO DE EVENTOS DE SEGURIDAD)
# ==============================================================================
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'audit_format': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)d] - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'formatter': 'audit_format',
        },
        'app_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'application.log'),
            'formatter': 'audit_format',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'fitzone_audit': {  # Logger personalizado para tu lógica de negocios
            'handlers': ['app_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = "FitZone.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Acá vive el index.html generado por "npm run build" (ver el catch-all en FitZone/urls.py)
        "DIRS": [FRONTEND_DIST_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "FitZone.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Adonde "collectstatic" junta todo para servirlo en producción (WhiteNoise)
STATIC_ROOT = BASE_DIR / "staticfiles"

# El build de Vite (base='/static/') referencia sus JS/CSS como /static/assets/...,
# así que montamos su carpeta "assets" bajo ese mismo prefijo. También servimos "public/"
# (favicon.svg, icons.svg) directo en la raíz de /static/, que es donde Vite los referencia.
STATICFILES_DIRS = [
    FRONTEND_DIST_DIR.parent / "public",
]
if (FRONTEND_DIST_DIR / "assets").exists():
    STATICFILES_DIRS.append(("assets", FRONTEND_DIST_DIR / "assets"))

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '120/min',
        'login': '5/min',
        'register': '5/min',
    },
}

# Configuración personalizada de los Tokens (Opcional pero recomendado para seguridad)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),     # El token de acceso dura 1 hora
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),        # El token de refresco dura 1 día
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,                   # Invalida el refresh token anterior al rotarlo
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,                          # Usa la misma llave secreta de tu Django
}
